### ISSUE TITLE
Any sample code?

### ISSUE THREAD

**Issue by RossenX** [simple64/simple64-netplay-server#11]
Hey dude, love your work i was just wondering if there is just a simple breakdown on how to connect to a server.
I'm basically trying to just add a few command-lines to the ui-console of mupen.

Sofar i got it mostly working and "M64CMD_NETPLAY_INIT" connects fine but "M64CMD_NETPLAY_CONTROL_PLAYER" always fails.
I assume i'm missing some steps that are required in getting it to work just from the ui-console.

Sofar i just start a server as stated in the docs here with "-name "Server Name"" then using the NETPLAY_INIT and NETPLAY_CONTROL_PLAYER before M64CMD_EXECUTE.

Do you maybe have some sample code or just a quick guide on getting it up and running. 

THANK YOU!

**Comment by loganmc10** [comment]
You can use mupen64plus-gui as a good sample:
https://github.com/m64p/mupen64plus-gui/blob/dabe17825cac476e87a72400fed2fa42cd27d9cb/interface/common.cpp#L270-L294

For ```(*CoreDoCommand)(M64CMD_NETPLAY_CONTROL_PLAYER, netplay_player, &reg_id)```, netplay_player should be the player number (1-4) that you want to take control of. mupen64plus-gui implements a lobby, so each player/user knows their number. The reg_id is basically a randomize string/player ID, you can see how it's generated in mupen64plus-gui in the code I linked

**Comment by RossenX** [comment]
Sweet! Thank you for the quick reply.
I got something i think almost working. It doesn't fail the register of the player anymore but it seems to hang on the registering and only continues if i turn off the server.
Is creating/joining a room required in order to get it to start the emulation or am i messing something up again?

Here is a little snippet of what i've added to the console-ui 

```
/* Save the configuration file again, if necessary, to capture updated
       parameters from plugins. This is the last opportunity to save changes
       before the relatively long-running game. */
    if (l_SaveOptions && (*ConfigHasUnsavedChanges)(NULL))
        (*ConfigSaveFile)();

    /* Init Netplay */
	if (Online == 1)
	{
		uint32_t version;
		if ((*CoreDoCommand)(M64CMD_NETPLAY_GET_VERSION, 0x010000, &version) == M64ERR_SUCCESS)
		{
			DebugMessage(M64MSG_INFO, "Netplay: using core version %u", version);

			if ((*CoreDoCommand)(M64CMD_NETPLAY_INIT, 45000, "127.0.0.1") == M64ERR_SUCCESS) {
				DebugMessage(M64MSG_INFO, "Netplay: init success");

				uint32_t reg_id = 0;
				while (reg_id == 0) {
					reg_id = rand();
					reg_id += Player;
				}

				DebugMessage(M64MSG_INFO, "Netplay: registering player: %d | id: %d", Player, reg_id);
				if ((*CoreDoCommand)(M64CMD_NETPLAY_CONTROL_PLAYER, Player, &reg_id) == M64ERR_SUCCESS) {
					DebugMessage(M64MSG_INFO, "Netplay: registered for player %d", Player);
				}
				else {
					DebugMessage(M64MSG_INFO, "Netplay: registered for player %d FAILED", Player);
				}

				DebugMessage(M64MSG_INFO, "\n->Netplay: Started Online as Player %d", Player);
			}
			else{DebugMessage(M64MSG_INFO, "Netplay: init FAILED");}
		}
	}
	else
	{
		DebugMessage(M64MSG_INFO, "\n->Netplay: Started Offline");
	}

    /* run the game */
	(*CoreDoCommand)(M64CMD_EXECUTE, 0, NULL);
```
![Screenshot_2](https://user-images.githubusercontent.com/11183420/122118580-dc050280-ce30-11eb-8677-7e3058d3bd0e.png)

**Comment by loganmc10** [comment]
Closing this, please reach out on discord if you still need help with this
